#-----------------------------------------------------------------
# pycparser: func_defs.py
#
# Using pycparser for printing out all the functions defined in a
# C file.
#
# This is a simple example of traversing the AST generated by
# pycparser. Call it from the root directory of pycparser.
#
# Eli Bendersky [https://eli.thegreenplace.net/]
# License: BSD
#-----------------------------------------------------------------
from __future__ import print_function
import sys

# This is not required if you've installed pycparser into
# your site-packages/ with setup.py
sys.path.extend(['.', '..'])

from pycparser import c_ast, parse_file


# A simple visitor for FuncDef nodes that prints the names and
# locations of function definitions.
class FuncDefVisitor(c_ast.NodeVisitor):
    def visit_FuncDef(self, node):
        final_product = ""
        #static or not
        if bool(node.decl.storage):
            final_product += node.decl.storage[0] + " "
        #this logic looks at the function declaration
        #if the function is a pointer
        if isinstance(node.decl.type.type, c_ast.PtrDecl):
            final_product += node.decl.type.type.type.type.names[0] + " *" + node.decl.type.type.type.declname
        #if it isn't a pointer
        else:
            final_product += node.decl.type.type.type.names[0] + " " + node.decl.type.type.declname
        #this logic looks at ALL arguments passed in function declaration
        final_product += "("
        #if there are arguments
        if node.decl.type.args is not None:
            for argument in range(len(node.decl.type.args.params)):
                #if an arg is a pointer
                if isinstance(node.decl.type.args.params[argument].type, c_ast.PtrDecl):
                    if isinstance(node.decl.type.args.params[argument].type.type.type, c_ast.TypeDecl):
                        final_product += node.decl.type.args.params[argument].type.type.type.type.names[0] + " *"
                    else:
                        final_product += node.decl.type.args.params[argument].type.type.type.names[0] + " " + "*"
                    #this is evaluating what type of pointer the argument is
                    if len(node.decl.type.args.params[argument].type.quals) != 0:
                        final_product += "* " + node.decl.type.args.params[argument].type.quals[0] + " "
                    if len(node.decl.type.args.params[argument].type.type.quals) != 0:
                        final_product += node.decl.type.args.params[argument].type.type.quals[0] + " * "
                #if not a pointer
                else: 
                    final_product +=  node.decl.type.args.params[argument].type.type.names[0] + " "
                #if the argument has a name
                if node.decl.type.args.params[argument].name is not None:
                    final_product += node.decl.type.args.params[argument].name
                #everything covered by the following logic is for functions passed as args and the nested implications
                if isinstance(node.decl.type.args.params[argument].type.type, c_ast.FuncDecl):
                    final_product += node.decl.type.args.params[argument].type.type.type.type.names[0] + " "
                    final_product += "(*" +  node.decl.type.args.params[argument].name + ")("
                    for nested_argument in range(len(node.decl.type.args.params[argument].type.type.args.params)):
                        if isinstance(node.decl.type.args.params[argument].type.type.args.params[nested_argument].type,  c_ast.PtrDecl):
                            final_product += node.decl.type.args.params[argument].type.type.args.params[nested_argument].type.type.type.names[0] + "* "
                        else:
                            final_product += node.decl.type.args.params[argument].type.type.args.params[nested_argument].type.type.names[0] + " "
                            if node.decl.type.args.params[argument].type.type.args.params[nested_argument].name is not None:
                                    final_product += node.decl.type.args.params[argument].type.type.args.params[nested_argument].name
                    final_product += ")"
                #formatting arg display
                if argument < len(node.decl.type.args.params):
                    final_product += ", "
        final_product += ")"
        print('%s at %s' % (final_product, node.decl.coord))


def show_func_defs(filename):
    # Note that cpp is used. Provide a path to your own cpp or
    # make sure one exists in PATH.
    ast = parse_file(filename, use_cpp=True,
                     cpp_args=r'-Iutils/fake_libc_include')

    v = FuncDefVisitor()
    v.visit(ast)


if __name__ == "__main__":
    if len(sys.argv) > 1:
        filename  = sys.argv[1]
    else:
        filename = 'examples/c_files/memmgr.c'

    show_func_defs(filename)
